# Generated by Django 5.2 on 2025-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='correo',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
