# Generated by Django 5.2 on 2025-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_email_contacto_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.TextField(),
        ),
    ]
